# Site settings
title: Doug Perkes
email: doug@dougperkes.com
description: > # this means to ignore newlines until "baseurl:"
  My name is Doug Perkes. I'm a geek, a programmer, a husband and father. I work out of my 
  home office in Peoria, Arizona as a Technical Evangelist for the Microsoft Developer & Platform
  Evangelism team. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dougperkes.github.io" # the base hostname & protocol for your site
twitter_username: dougperkes
github_username:  dougperkes

# Build settings
markdown: kramdown
